receiver:
	gcc.exe -fPIC -shared -o ./bin/receiver.dll -I"C:/Program Files/Zulu/zulu-17/include" -I"C:/Program Files/Zulu/zulu-17\include/win32" ./src/receiver.c
sender:
	gcc.exe -fPIC -shared -o ./bin/sender.dll -I"C:/Program Files/Zulu/zulu-17/include" -I"C:/Program Files/Zulu/zulu-17/include/win32" ./src/sender.c
all: receiver sender