create_semaphore:
	gcc create_semaphore.c -o create_semaphore -pthread
wait_semaphore:
	gcc wait_semaphore.c -o wait_semaphore -pthread	
post_semaphore:
	gcc post_semaphore.c -o post_semaphore -pthread
unlink_semaphore:
	gcc unlink_semaphore.c -o unlink_semaphore -pthread
all: create_semaphore wait_semaphore post_semaphore unlink_semaphore
